### ISSUE TITLE
New Player list in Admin Panel is not working

### ISSUE THREAD

**Issue by Shd0ww** [coalaura/opfw-admin#49]
**Which clusters panel is this on?**
c2, c3, etc.

**Describe the bug**
I am from legacy roleplay Bangladesh. New player list in admin panel is not working. 

**Expected behavior**
Expecting it should be fixed as soon as possible.

**Screenshots**
(https://i.vgy.me/WfZhm4.png)](https://i.vgy.me/WfZhm4.png)

**Comment by coalaura** [comment]
fixed

**Comment by Shd0ww** [comment]
It is still not working. :( 
This is my panel : https://p80.admin.opfw.me/new_players

**Comment by Shd0ww** [comment]
It still not working. 
Here's the clip : https://youtu.be/OvRS309Vcng

**Comment by coalaura** [comment]
i fixed and tested it, are you sure you setup your panel correctly and that there are actually new players?
